### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by xmha97** [m-i-n-a-r/tasticalendar#1]
Please upload the APK file to GitHub release page.

**Comment by m-i-n-a-r** [comment]
This is a library, there's no apk file. But, you can find an example of implementation in my [Birday App](https://github.com/m-i-n-a-r/birday/commit/84693a13c993f138152031ed6cd69b61957507e1). I'll add a full set of examples and documentation soon, I'm still working out some minor bugs. 😄

**Comment by xmha97** [comment]
Ok, sorry.
