### ISSUE TITLE
Wrong month names in Croatian

### ISSUE THREAD

**Issue by m-i-n-a-r** [m-i-n-a-r/tasticalendar#4]
As reported in Birday, month names are incorrect in Croatian, and potentially in other languages.

**Comment by m-i-n-a-r** [comment]
I'm not sure this can be fixed, because the month names are taken directly from Android. I'll update the issue as soon as I investigate.

**Comment by m-i-n-a-r** [comment]
https://github.com/m-i-n-a-r/tasticalendar/blob/68d3ed7a756a6e156a908d99e6393c1024a71177/tasticalendar/src/main/java/com/minar/tasticalendar/core/TastiCalendarMonth.kt#L415 Here's the problem. The name of the month is taken from a date, and the date is has a day. The name of the month changes depending on the day, hence the bug. I need a way to take the day of the month in the "generic" form.

**Comment by DominikNovosel** [comment]
I just confirmed that Czech, Polish, Russian and most likely other Slavic languages are also affected by this issue. If someone is able to, it might be worth checking other languages that make use of cases.

**Comment by m-i-n-a-r** [comment]
Yep, and the above line of code is the problem. My fault! I'll fix this in the library and update the library inside Birday before releasing the final version of the update 👍

**Comment by DominikNovosel** [comment]
> I need a way to take the day of the month in the "generic" form.

Something like this? 
https://stackoverflow.com/a/25329549

Granted, it's in Java, but it's a good starting point since the poster understands the problem.

**Comment by m-i-n-a-r** [comment]
Fixed it in v1.3.6! And updated Birday to use the fixed version. I should release this fix as a beta update tomorrow 👍
